version: '3'

services:

  drools-wb:
    container_name: drools-wb
    build:
      dockerfile: Dockerfile
      context: ./drools-workbench
    ports:
      - 8001:8001
      - 28080:8080
    network_mode: default
#    volumes:
#      - E:\Workspace\docker\jbpmn-workbench\repository:/opt/jboss/wildfly/bin/.niogit:Z

  kie-server:
    container_name: kie-server
    image: jboss/kie-server-showcase:7.15.0.Final
    links:
      - drools-wb:kie_wb
    ports:
      - 8080:8080
    network_mode: default
    depends_on:
      - drools-wb
    environment:
      - KIE_WB_PORT_8080_TCP=tcp://kie_wb:8080
      - KIE_WB_ENV_KIE_CONTEXT_PATH=drools-wb
      - KIE_WB_PORT_8080_TCP_ADDR=kie_wb

volumes:
  git-volume:
