FROM jboss/drools-workbench-showcase:7.15.0.Final
LABEL MAINTAINER="Jan van Lil"

#RUN ./add-user.sh -a -u 'admin' -p 'admin1!' -g 'admin' && \
#    ./add-user.sh -a -u 'analyst' -p 'analyst1!' -g 'analyst' && \
#    ./add-user.sh -a -u 'developer' -p 'developer1!' -g 'developer' && \
#    ./add-user.sh -a -u 'manager' -p 'manager1!' -g 'manager' && \
#    ./add-user.sh -a -u 'user' -p 'user1!' -g 'user'

